# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.TextField(default='XXX.com'),
        ),
    ]
